name: "Publish Stable Version"

on:
  push:
    branches:
      - develop

jobs:
  publish:
    name: 🚀 Publishing to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Set variables
        run: |
          echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "VERSION=$(npm view ./packages/${{ github.event.inputs.name }} version)" >> $GITHUB_ENV

      - name: Build & Publish
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build
          pnpm version ${{ env.VERSION }}-alpha.${{ env.COMMIT_ID }}
          pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
